# Generated by Django 3.2.25 on 2026-05-04

from django.db import migrations


UPDATE_PROJECTS_ANON_PERMISSION_SQL = """
    UPDATE projects_project
    SET anon_permissions = array_append(COALESCE(anon_permissions, ARRAY[]::text[]), '{permission}')
    WHERE
        is_private = false
        AND
        NOT ('{permission}' = ANY(COALESCE(anon_permissions, ARRAY[]::text[])))
"""

UPDATE_PROJECTS_PUBLIC_PERMISSION_SQL = """
    UPDATE projects_project
    SET public_permissions = array_append(COALESCE(public_permissions, ARRAY[]::text[]), '{permission}')
    WHERE
        is_private = false
        AND
        NOT ('{permission}' = ANY(COALESCE(public_permissions, ARRAY[]::text[])))
"""


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0068_project_archived_code"),
    ]

    operations = [
        migrations.RunSQL(
            UPDATE_PROJECTS_ANON_PERMISSION_SQL.format(permission="view_schedule"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            UPDATE_PROJECTS_PUBLIC_PERMISSION_SQL.format(permission="view_schedule"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            UPDATE_PROJECTS_ANON_PERMISSION_SQL.format(permission="view_gantt"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            UPDATE_PROJECTS_PUBLIC_PERMISSION_SQL.format(permission="view_gantt"),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
