# Generated by Django 3.2.25 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0069_public_projects_add_schedule_gantt_view_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_schedule_activated",
            field=models.BooleanField(blank=True, default=True, verbose_name="active schedule and gantt panels"),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="is_schedule_activated",
            field=models.BooleanField(blank=True, default=True, verbose_name="active schedule and gantt panels"),
        ),
    ]
