# Generated by Django 3.2.25 on 2026-04-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_add_schedule_project_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_sc_entity__fa00ef_idx',
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['entity_type', 'entity_id'], name='schedule_sc_entity__c3d2db_idx'),
        ),
    ]
