# Generated by Django 3.2.25 on 2026-06-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_schedule_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='estimated_hours',
        ),
    ]
